CKBProject/urls.py
from django.contrib import admin
from django.urls import path
from CKBApp.views import create_tournament_view, manage_payload,home_view ,evaluate_battle_view ,joinTeam, invite_friends_view, close_tournament_view, tournament_ranking_view, tournament_details_view, login_view, loginEducator_view, home_student_view, home_educator_view, registration_view, check_email_exists, logoutEducator_view, battle_details_view, ongoing_tournament_details_view, enrolled_tournament_view, logout_view, join_battle_view, check_enrollment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login-page'),
    path('loginEducator/', loginEducator_view, name='loginEducator-page'),
    path('registration/', registration_view, name='registration-page'),
    path('home/student/', home_student_view, name='home-student'),
    path('home/educator/', home_educator_view, name='home-educator'),
    path('check-email-exists/', check_email_exists, name='check-email-exists'),
    path('createTournament/', create_tournament_view, name='create-tournament'),
    path('tournament-details/<int:tournament_id>/', tournament_details_view, name='tournament-details'),
    path('logout/', logoutEducator_view, name='logout'),
    path('logout/student/', logout_view, name='logoutStudent-page'),
    path('battle-details/<int:battle_id>/', battle_details_view, name='battle-details'),
    path('rankingTournament/<int:tournament_id>/', tournament_ranking_view , name='ranking-tournament'),
    path('close-tournament/<int:tournament_id>/', close_tournament_view, name='close-tournament'),
    path('ongoing-tournament-details/<int:tournament_id>/', ongoing_tournament_details_view, name='ongoing-tournament-details'),
    path('enrolledTo/<int:tournament_id>/', enrolled_tournament_view, name='enrolled_tournament'),
    path('join-battle/<int:battle_id>/', join_battle_view, name='join-battle'),
    path('check-enrollment/<int:battle_id>/', check_enrollment, name='check-enrollment'),
    path('invite-friends/<int:battle_id>/', invite_friends_view, name='inviteFriends-page'),
    path('joinTeam/<int:team_id>/<int:battle_id>/<int:invite_id>/', joinTeam, name='joinTeam'),
    path('evaluate-battle/<int:battle_id>/', evaluate_battle_view, name='evaluate-battle'),
    path('goHome/', home_view, name='go-home'),
    path('managePayload/', manage_payload, name='manage-payload'),
]
 

CKBApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Tournament(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    submission_deadline = models.DateField()
    ending_date = models.DateField()
    def __str__(self):
        return self.name

class Battle(models.Model):
    name = models.CharField(max_length=100)
    registration_deadline = models.DateField()
    submission_deadline = models.DateField()
    max_team_students = models.IntegerField()
    min_team_students = models.IntegerField()
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    manually_evaluated = models.BooleanField(default=False)
    code_kata = models.FileField(upload_to='media/', blank= False, default= None)
    repository_created = models.BooleanField(default=False)
    url_repository = models.CharField(max_length=100, blank=True)
    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    user_type = models.CharField(max_length=50)
    github_username = models.CharField(max_length=100, blank=True)
    def __str__(self):
        return f"{self.name} {self.surname}"

class Team(models.Model):
    name = models.CharField(max_length=100)
    num_members = models.IntegerField()
    battle = models.ForeignKey(Battle, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, default=None)
    def __str__(self):
        return self.name
    
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tournaments = models.ManyToManyField(Tournament, related_name='students', blank=True)
    teams = models.ManyToManyField(Team, related_name='students', blank=True)
    def __str__(self):
        return f"Student: {self.user.name} {self.user.surname}"

class Educator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tournaments = models.ManyToManyField(Tournament, related_name='educators', blank=True)
    battles_managed = models.ManyToManyField(Battle, related_name='educators', blank=True)
    def __str__(self):
        return f"Educator: {self.user.name} {self.user.surname}"

class Invite(models.Model):
    user_invited = models.ForeignKey(User, on_delete=models.CASCADE, related_name='invites_received')
    user_who_invite = models.ForeignKey(User, on_delete=models.CASCADE, related_name='invites_sent')
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)
    def __str__(self):
        return f"Invite from {self.user_who_invite} to {self.user_invited} for team {self.team}"

class TournamentRanking(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, blank= False)
    score = models.IntegerField(default=0)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, blank= False)
    def __str__(self):
        return f"Tournament Ranking: Student {self.student.user.name} - Score: {self.score} - Tournament: {self.tournament.name}"
    
class TeamBattleRanking(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, blank= False)
    score = models.IntegerField(default=0)
    battle = models.ForeignKey(Battle, on_delete=models.CASCADE, blank= False)
    def __str__(self):
        return f"Team: {self.team.name} | Battle: {self.battle.name} | Score: {self.score}"
    
class StudentBattleRanking(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, blank= False)
    score = models.IntegerField(default=0)
    battle = models.ForeignKey(Battle, on_delete=models.CASCADE, blank= False)
    def __str__(self):
        return f"Student: {self.student.user.name} {self.student.user.surname} | Battle: {self.battle.name} | Score: {self.score}"
    
class Repository(models.Model):
    battle = models.ForeignKey('Battle', on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    link = models.CharField(max_length=255)

CKBApp/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from datetime import datetime
from django.contrib.sessions.models import Session
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from CKBApp.create_repositories import create_github_repository
#from create_repositories import create_github_repositories
from .forms import InvitationForm, LoginForm, PermissionForm, RegistrationForm, TeamRegistrationForm, TournamentCreationForm
from .models import Battle, Invite, Student, Educator, StudentBattleRanking, Team, TeamBattleRanking, Tournament, TournamentRanking, User
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import get_object_or_404

def home_student_view(request):
    #create_github_repositories()
    # Get the user ID from the session
    user_id = request.session.get('user_id')
    # Retrieve the student associated with the user ID
    student = Student.objects.get(user_id=user_id)
    student_name = student.user.name
    current_date = timezone.now().date()
    user_tournaments_ongoing = student.tournaments.filter(submission_deadline__gte=current_date)
    user_tournaments_expired = student.tournaments.filter(submission_deadline__lt=current_date)
    all_tournaments_expired = Tournament.objects.filter(submission_deadline__lt=current_date)
    user = User.objects.get(id=user_id)

    invites = Invite.objects.filter(user_invited=user)

    # Filter out tournaments where the submission deadline has passed
    available_tournaments = Tournament.objects.filter(submission_deadline__gte=current_date).exclude(pk__in=student.tournaments.all())
    
    return render(request, 'CKBApp/HomePageStudent.html', {'student_name': student_name, 'all_tournaments_expired': all_tournaments_expired ,'user_tournaments_ongoing': user_tournaments_ongoing, 'user_tournaments_expired': user_tournaments_expired, 'available_tournaments': available_tournaments, 'invites': invites})


def invite_friends_view(request, battle_id):
    battle = Battle.objects.get(id=battle_id)
    user_id = request.session.get('user_id')
    student = Student.objects.get(user_id=user_id)
    user = User.objects.get(id=user_id)
    invitation_form = InvitationForm()
    team = Team.objects.get(battle=battle, creator=user)

    if request.method == 'POST':
        invitation_form = InvitationForm(request.POST)
        if invitation_form.is_valid():
            mate_email = invitation_form.cleaned_data['mate_email']
            try:
                invited_user = User.objects.get(email=mate_email)
            except User.DoesNotExist:
                messages.error(request, "User with the given name does not exist.")
                return render(request, 'CKBApp/InviteFriends.html')
            if Invite.objects.filter(team=team, user_invited=invited_user).exists():
                # Display an error message if an invitation already exists
                messages.error(request, 'This student has already been invited to join the team.')
            else:
                # Get the user ID from the session
                user_id = request.session.get('user_id')
                creator_user= User.objects.get(id=user_id)

                student = Student.objects.get(user_id=user_id)

                # Create a new Team instance
                invite = Invite (
                    user_invited = invited_user,
                    user_who_invite = creator_user,
                    team = team,
                    accepted = False
                )
                invite.save()
                invitation_form = InvitationForm()     
        else:
           invitation_form = InvitationForm()     
    
    context = {
        'battle_name' : battle.name,
        'team_name': team.name,
        'battle_max_team_stud' : battle.max_team_students,
        'battle_min_team_stud' : battle.min_team_students,
        'invitation_form': invitation_form,   
    }
    return render(request, 'CKBApp/InviteFriends.html', context)

     
def enrolled_tournament_view(request, tournament_id):
    # Get the user ID from the session
    user_id = request.session.get('user_id')
    # Retrieve the student associated with the user ID
    student = Student.objects.get(user_id=user_id)
    user = User.objects.get(id=user_id)
    student_name = student.user.name
    student_id = student.id
    if request.method == 'POST':
        # Get the tournament to enroll in
        tournament = Tournament.objects.get(pk=tournament_id)
        current_date = timezone.now().date()
        if current_date <= tournament.submission_deadline:
            existing_ranking = TournamentRanking.objects.filter(student=student, tournament=tournament).exists()
            if not existing_ranking:
                student.tournaments.add(tournament)
                tournament_ranking = TournamentRanking (
                    student = student,
                    tournament = tournament
                )
                tournament_ranking.save()
    tournament = Tournament.objects.get(pk=tournament_id)
    battles = Battle.objects.filter(tournament=tournament)
    enrolled_battles = battles.filter(team__students=student)
    battle_team_created = enrolled_battles.filter(team__creator=user)
    today = datetime.now().date()

    tournament_name = tournament.name
    
    context = {
            'tournament': tournament,
            'tournament_name': tournament_name,
            'battles': battles,
            'student_name': student_name,
            'student' : student,
            'enrolled_battles': enrolled_battles,
            'battle_team_created': battle_team_created,
            'today': today
    }
    return render(request, 'CKBApp/EnrolledTournamentDetails.html', context)


def tournament_ranking_view(request, tournament_id):
   # Retrieve the tournament details using the tournament_id
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    tournament_rankings = TournamentRanking.objects.filter(tournament=tournament).order_by('-score')
    context = {
        'tournament': tournament,
        'tournament_rankings': tournament_rankings
    }
    return render(request, 'CKBApp/Ranking.html', context)

def home_educator_view(request):
    # Get the user ID from the session
    user_id = request.session.get('user_id')
    # Retrieve the educator associated with the user ID
    educator = Educator.objects.get(user_id=user_id)
    educator_name = educator.user.name
    user_tournaments = educator.tournaments.all()
    other_tournaments = Tournament.objects.exclude(pk__in=[tournament.pk for tournament in user_tournaments])
    return render(request, 'CKBApp/HomePageEducator.html', {'user_tournaments': user_tournaments, 'other_tournaments': other_tournaments,'educator_name': educator_name})

def ongoing_tournament_details_view(request, tournament_id):
    try:
        tournament = Tournament.objects.get(pk=tournament_id)
        battles = Battle.objects.filter(tournament=tournament)
        context = {
            'tournament': tournament,
            'battles': battles,
        }
        return render(request, 'CKBApp/OngoingTournamentStatus.html', context)
    except Tournament.DoesNotExist:
        # Handle case where tournament does not exist
        return render(request, 'CKBApp/tournament_not_found.html')

def tournament_details_view(request, tournament_id):
    # Get the user ID from the session
    user_id = request.session.get('user_id')
    # Retrieve the educator associated with the user ID
    educator = Educator.objects.get(user_id=user_id)
    educator_name = educator.user.name
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    permission_form = PermissionForm(prefix='permission_form')

    if request.method == 'POST':
        if 'create_battle_form' in request.POST:
            name = request.POST.get('name')
            registration_deadline = request.POST.get('registration_deadline')
            submission_deadline = request.POST.get('submission_deadline')
            max_team_students = request.POST.get('maximum_number_of_students')
            min_team_students = request.POST.get('minimum_number_of_students')
            registration_deadline = datetime.strptime(registration_deadline, '%Y-%m-%d').date()
            submission_deadline = datetime.strptime(submission_deadline, '%Y-%m-%d').date()
            github_username = request.POST.get('github_username')
            
            code_kata = request.FILES.get('code_kata')

            # Create a new Battle instance
            battle = Battle(
                        name=name,
                        tournament=tournament,
                        registration_deadline = registration_deadline,
                        submission_deadline = submission_deadline,
                        max_team_students = int(max_team_students),
                        min_team_students = int(min_team_students),
                        code_kata= code_kata
                    )
            current_date = timezone.now().date()
            if current_date <= battle.registration_deadline and current_date <= battle.submission_deadline and battle.registration_deadline <= battle.submission_deadline:
                if battle.registration_deadline >= tournament.submission_deadline and battle.submission_deadline >= tournament.submission_deadline:
                    existing_battle = Battle.objects.filter(name=battle.name, tournament=tournament).exists()
                    if not existing_battle:
                        battle.save()     
     
        elif 'permission_form' in request.POST:  # Check if the permission form is submitted
                permission_form = PermissionForm(request.POST, prefix='permission_form')  # Add prefix to distinguish form fields

CKBApp/templates/CKBApp/EnrolledTournamentDetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeKataBattle - Student Interface</title>
    <link rel="stylesheet" href="{% static 'CKBApp/css/Studentstyle.css' %}">
</head>
<body>
    <header>
        <h1>Hi {% if student_name %}{{ student_name }}{% else %}Student{% endif %}! Are you ready to learn?</h1>
        <button id="back">Back</button>
        <button id="home">Home</button>
        <button id="logout">Logout</button>
    </header>
<div class="container">
    <div class="right">
        <section class= "battles">
            <h3>Battles</h3>
            <div>
                <ul>
                    {% for battle in battles %}
                        <h3>{{ battle.name }}</h3>
                        {% if battle in enrolled_battles %}
                            <p class="badge-label">Joined</p>
                        <br>
                        {% endif %}
                            <button id="battleStatus" onclick="checkEnrollment('{{ battle.id }}')">View Battle Details</button>
                        
                        {% if battle in battle_team_created %}
                            {% if battle.submission_deadline < today %}
                                <button id="inviteFriends" onclick="inviteFriends('{{ battle.id }}')">Invite your friends</button>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>     
        </section>
    </div>

    <div class="left">
        <section class = "ranking">
            
            <div class="battle">
                <h4>Tournament {% if tournament_name %}{{ tournament_name }}{% else %}x{% endif %} ranking</h4>
            </div>
            
            <div>
                <button class="view-details-battle" onclick="viewTournamentRanking('{{ tournament.id }}')">View Ranking</button>
            </div>
            </section>
    </div>
</div>
</body> 
<script>

        document.getElementById('back').addEventListener('click', function() {
            // Perform back action
            window.history.back();
        });

        document.getElementById('home').addEventListener('click', function() {
            // Perform home action
            window.location.href = "{% url 'go-home' %}";
        });

    document.getElementById('logout').addEventListener('click', function() {
        // Perform logout action
        window.location.href = "{% url 'logoutStudent-page' %}";
    });

    function inviteFriends(battleId) {
            // Redirect the user to the tournament details page with the correct ID
            window.location.href = "/invite-friends/" + battleId + "/";
        }


    function checkEnrollment(battleId) {
        fetch(`/check-enrollment/${battleId}/`)
        .then(response => response.json())
        .then(data => {
            if (data.is_part_of_team) {
                // Redirect to battle details page
                window.location.href = "/battle-details/" + battleId + "/";
            } else {
                // Redirect to join battle page
                window.location.href = "/join-battle/" + battleId + "/";
            }
        })
        .catch(error => {
            console.error('Error:', error);
            // Handle error
        });
    }

    function viewTournamentRanking(tournamentId){
        window.location.href = "/rankingTournament/" + tournamentId + "/";
    }
</script>
</html>
                               

CKBApp/templates/CKBApp/Evaluate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Educator Evaluation</title>
    <link rel="stylesheet" href="{% static 'CKBApp/css/Evaluatestyle.css' %}">
</head>

<body>

    <header>
        <h1>Educator Evaluation</h1>
        <button id="back">Back</button>
        <button id="home">Home</button>
        <button id="logout">Logout</button>
    </header>

    <form id="form" method="post">
        {% csrf_token %}
        <ul class="team-list">
            <h2>Teams Evaluation</h2>
            {% for team in battle_teams %}
                <li class="team-item">
                    <span>{{ team.name }}</span>
                    <input type="number" name="score_{{ team.id }}" placeholder="Enter score" required min="0" max="100">
                    <input type="hidden" name="teamid_{{ team.id }}" value="{{ team.id }}">    
                </li>
            {% endfor %}
            <h2>Students Evaluation</h2>
            {% for student, team in battle_students.items %}
                <li class="team-item">
                    <span>{{ student.user.name }} in {{ team.name }}</span>
                    <input type="number" name="score_{{ student.id }}" placeholder="Enter score" required min="0" max="100"> 
                </li>
            {% endfor %}
        </ul>
        <div class="team-list">
        <button type="submit" class="evaluate-button" >Evaluate</button>
        </div>
    </form>
<script>
    
        document.getElementById('back').addEventListener('click', function() {
        // Perform back action
        window.history.back();
        });

        document.getElementById('home').addEventListener('click', function() {
        // Perform home action
        window.location.href = "{% url 'go-home' %}";
        });

    document.getElementById('logout').addEventListener('click', function() {
        // Perform logout action
        window.location.href = "{% url 'logout' %}";
    });
</script>

    
</body>

</html>

CKBApp/templates/CKBApp/LogIn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeKataBattle</title>
    <link rel="stylesheet" href="{% static 'CKBApp/css/LogStyle.css' %}">
</head>
<body>
    <form name="loginForm" method="post">
        <div class="formCo">
            {% csrf_token %}
            <h2>CodeKataBattle</h2>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <label for="{{ form.email.id_for_label }}">Insert your mail:</label>
            {{ form.email }}
            <label for="{{ form.password.id_for_label }}">Insert your password:</label>
            {{ form.password }}
            <input type="hidden" name="type" value="log"/>
            <input type="submit" value="Sign in"/>
            <div>
            <p>Don't you have an account?<a href="{% url 'registration-page' %}"> Sign up</a></p>
            <p> Are you an Educator? <a href= "{% url 'loginEducator-page' %}"> Sign in as an educator</a></p>
        </div>
    </form>
</body>
</html>

CKBApp/templates/CKBApp/Registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'CKBApp/css/RegistrationStyle.css' %}">
    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <form name="registrationForm" method="post" action="{% url 'registration-page' %}">
        {% csrf_token %}
        <div class="formCo">
            <h2>Registration</h2>
            {{ form.as_p }}
            <input type="submit" value="Register">
        </div>
    </form>

    <!-- Add AJAX script -->
    <script>
        $(document).ready(function () {
            $('#id_email').on('blur', function () {
                var email = $(this).val();
                // Check email existence using AJAX
                $.ajax({
                    url: "{% url 'check-email-exists' %}",
                    method: "GET",
                    data: { 'email': email },
                    success: function (data) {
                        if (data.exists) {
                            alert('User with this email already exists.');
                        }
                    }
                });
            });
        });
    </script>
</body>
</html>

CKBApp/templates/CKBApp/TournamentDetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tournament Details</title>
    <link rel="stylesheet" href="{% static 'CKBApp/css/EducatorStyle.css' %}">
</head>
<body>
    <header>
        <h1>Hi {% if educator_name %}{{ educator_name }}{% else %}Educator{% endif %}! Start Work</h1>
        <button id="back">Back</button>
        <button id="home">Home</button>
        <button id="logout">Logout</button>
    </header>
    <div class="container">
        <div class="right">
            <div class="search-bar">
                <section>
                    <h3>{{ tournament.name }} </h3>
                    <p>{{ tournament.description }} </p>
                    <br>
                    <div>
                        <button id="viewRanking" onclick="viewRanking({{ tournament.id }})">View Ranking</button>
                    </div>
                    <br>
                    <h4>WARNING! This action is irreversible.</h4>
                    <button id="badge-label" onclick="closeTournament({{ tournament.id }})">Close Tournament</button>

                    <form method="post">
                        {% csrf_token %}
                        <h4>Permission</h4>
                        {{ permission_form.as_p }}
                        <button type="submit" name="permission_form">Grant Permission</button>
                    </form>
                    <br>
                    <div>
                        <h4>Battles</h4>
                        <ul>
                            {% if battles %}
                            {% for battle in battles %}
                                <h3>{{ battle.name }}</h3>
                                <button id="battleStatus" onclick="viewBattleDetails({{ battle.id }})">View Battle Details</button>
                                
                                {% if battle.submission_deadline < today %}
                                    {% if not battle.manually_evaluated %}
                                        <button id="evaluate" onclick="evaluateBattle({{ battle.id }})">Evaluate</button>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            {% else %}
                            <p>No battles found.</p>
                            {% endif %}
                        </ul>
                    </div> 
                </section>       
            </div>
        </div>
        
                
        <div class="left">
            
            <section class="create-battle">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2>Create New Battle</h2>
                    <label for="id_name">Name:</label>
                    <input type="text" id="id_name" name="name" required>
                    <label for="id_minimum_number_of_students">Minimum Number of Students:</label>
                    <input type="number" id="id_minimum_number_of_students" name="minimum_number_of_students" required>
                    <label for="id_maximum_number_of_students">Maximum Number of Students:</label>
                    <input type="number" id="id_maximum_number_of_students" name="maximum_number_of_students" required>
                    <label for="id_registration_deadline">Registration Deadline:</label>
                    <input type="date" id="id_registration_deadline" name="registration_deadline" required>
                    <label for="id_submission_deadline">Submission Deadline:</label>
                    <input type="date" id="id_submission_deadline" name="submission_deadline" required>
                    <label for="id_code_kata">Code Kata File:</label>
                    <input type="file" id="id_code_kata" name="code_kata" required>
                    <input type="submit" id="createBattle" name="create_battle_form" value="Create Battle">
                </form>
            </section> 
            </div>
    </div>
    <script>

        document.getElementById('back').addEventListener('click', function() {
        // Perform back action
        window.history.back();
        });

        document.getElementById('home').addEventListener('click', function() {
        // Perform home action
        window.location.href = "{% url 'go-home' %}";
        });

        document.getElementById('logout').addEventListener('click', function() {
                // Perform logout action
                window.location.href = "{% url 'logout' %}";
        });

        function viewBattleDetails(battleId) {
            // Redirect the user to the tournament details page with the correct ID
            window.location.href = "/battle-details/" + battleId + "/";
        }

        function viewRanking(tournamentId) {
            // Redirect the user to the tournament details page with the correct ID
            window.location.href = "/rankingTournament/" + tournamentId + "/";
        }

        function closeTournament(tournamentId) {
            // Send a POST request to the close tournament URL
            fetch(`/close-tournament/${tournamentId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'  // Include CSRF token in the request headers
                }
            })
            .then(response => {
                // Handle response (e.g., redirect to another page)
                window.location.href = '/home/educator';  // Redirect to the home page or an appropriate page
            })
            .catch(error => {
                console.error('Error:', error);
                // Handle error (e.g., display an error message)
            });
        }

        function evaluateBattle(battleId) {
            // Redirect the user to the evaluate battle page with the correct ID
            window.location.href = "/evaluate-battle/" + battleId + "/";
        }

    </script>
            